apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: velero
  namespace: monitoring
spec:
  groups:
  - name: velero
    rules:
    - alert: VeleroUnsuccessfulBackup
      annotations:
        description: Velero backup was not successful for {{ $labels.schedule }}.
        summary: Velero backup for schedule was unsuccessful.
      expr: |
        (
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*6hrly.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 6) and ON() hour() >= 6.30 <= 18.30)
          or
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*daily.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 24) and ON() day_of_week() != 0)
          or
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*weekly.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 24 * 7))
        )
      for: 15m
      labels:
        schedule: '{{ $labels.schedule }}'
        severity: warning
    - alert: VeleroNoFirstSuccessfulBackup
      annotations:
        description: Velero backup was not successful for {{ $labels.schedule }}.
        summary: Velero backup for schedule was unsuccessful.
      expr: |
        (
          (
            count by(__name__, schedule) (velero_backup_attempt_total{schedule=~".*6hrly.*"}) > 0
            unless
              velero_backup_last_successful_timestamp
          )
          or
          (
            count by(__name__, schedule) (velero_backup_attempt_total{schedule=~".*daily.*"}) > 0
            unless
              velero_backup_last_successful_timestamp
          )
          or
          (
            count by(__name__, schedule) (velero_backup_attempt_total{schedule=~".*weekly.*"}) > 0
            unless
              velero_backup_last_successful_timestamp
          )
        )
      for: 15m
      labels:
        schedule: '{{ $labels.schedule }}'
        severity: critical
