apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 20.1.1
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: ccm-hetzner
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/ccm-hetzner
      targetRevision: 20.1.1
      helm:
        valueFiles:
          - $values/k8s/backup-server/argocd-apps/values-ccm-hetzner.yaml
    - repoURL: https://github.com/asifulhaque786/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
