seaweedfs:
  master:
    data:
      type: "persistentVolumeClaim"
      size: "10Gi"
      storageClass: "zfs-localpv"
    logs:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "zfs-localpv"
  filer:
    encryptVolumeData: true
    data:
      type: "persistentVolumeClaim"
      size: "100Gi"
      storageClass: "zfs-localpv"
    logs:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "zfs-localpv"
  s3:
    enabled: true
    enableAuth: true
    ingress:
      enabled: true
      className: "traefik"
      # host: false for "*" hostname
      host: "seaweedfs.cluster.local"
      path: "/"
      pathType: Prefix
      # additional ingress annotations for the s3 endpoint
      annotations: {}
      tls: []