apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "21.0.0"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: erpnext
  namespace: argocd
spec:
  destination:
    namespace: erpnext
    server: https://kubernetes.default.svc
  sources:
    - path: k8s/kubeaid-demo-local/argocd-apps/charts/erpnext
      repoURL: https://github.com/btwshivam/kubeaid-config.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-local/argocd-apps/values-erpnext.yaml
    - repoURL: https://github.com/btwshivam/kubeaid-config.git
      targetRevision: main
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
